article/urls.py
from django.urls import path
from .import views
app_name='article'
urlpatterns = [
    # path函数将url映射到视图
    path('category/',views.category_list,name='category_list'),
    path('category/<name>/',views.sort_by_category,name='sort_by_category'),
    path('', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include

# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('article.urls',namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
# 记得导入
from django.urls import reverse
# 博客文章数据模型

class category(models.Model):
    """
    栏目的 Model
    """
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    # 文章栏目的 “一对多” 外键
    category = models.ForeignKey(
        category,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    #点击数
    total_views = models.PositiveIntegerField(default=0)
    #图片
    pic = models.ImageField(upload_to='pic/%Y%m%d/', blank=True)
    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body','category','pic')

article/views.py
from django.shortcuts import render

# Create your views here.
import markdown
# 导入数据模型ArticlePost
from .models import ArticlePost,category

from comment.models import Comment
# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
# 引入User模型
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
# 引入 Q 对象
from django.db.models import Q

def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        if order == 'total_views':
            # 用 Q对象 进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    paginator = Paginator(article_list, 8)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    for article in articles:
        article.body = markdown.markdown(article.body,
                                         extensions=[
                                             # 包含 缩写、表格等常用扩展
                                             'markdown.extensions.extra',
                                             # 语法高亮扩展
                                             'markdown.extensions.codehilite',
                                         ])
    # 增加 search 到 context
    context = { 'articles': articles, 'order': order, 'search': search }

    return render(request, 'article/list.html', context)

def category_list(request):
    categories=category.objects.all()
    content={'categories':categories}
    return render(request,'article/category.html',content)

def sort_by_category(request,name):
    article_list=ArticlePost.objects.filter(category__title=name)#一个等于号

    '''allarticles=ArticlePost.objects.all()
    article_list=[article for article in allarticles if article.column_id and article.column.title==name]'''
    paginator = Paginator(article_list, 8)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    for article in articles:
        article.body = markdown.markdown(article.body,
                                         extensions=[
                                             # 包含 缩写、表格等常用扩展
                                             'markdown.extensions.extra',
                                             # 语法高亮扩展
                                             'markdown.extensions.codehilite',
                                         ])
    context = {'articles': articles}
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    # 取出文章评论
    comments = Comment.objects.filter(article=id)
    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    # 将markdown语法渲染成html样式  增加文章目录
    md = markdown.Markdown(
        extensions=[
        # 包含 缩写、表格等常用扩展
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        # 目录扩展
        'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body)

    # 添加comments上下文
    context = { 'article': article, 'toc': md.toc, 'comments': comments }
    return render(request, 'article/detail.html', context)

# 写文章的视图
@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            # 新增的代码
            if request.POST['category'] != 'none':
                new_article.category = category.objects.get(id=request.POST['category'])
            if 'pic' in request.FILES:
                new_article.pic = request.POST['pic']
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 新增及修改的代码
        categories = category.objects.all()
        context = {'article_post_form': article_post_form, 'categories': categories}
        # 返回模板
        return render(request, 'article/create.html', context)

@login_required(login_url='/userprofile/login/')
def article_delete(request, id):

    # 根据 id 获取需要删除的文章
    article = ArticlePost.objects.get(id=id)
    if request.user.is_superuser != 1:
        return HttpResponse("抱歉，你无权删除这篇文章。")
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")

# 更新文章
# 提醒用户登录
@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 判断用户是否为 POST 提交表单数据
    if request.user.is_superuser != 1:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article_cd = article_post_form.cleaned_data
            article.title = request.POST['title']
            article.body = request.POST['body']
            # 新增的代码
            if request.POST['category'] != 'none':
                article.category = category.objects.get(id=request.POST['category'])
            else:
                article.category = None
            if 'pic' in request.FILES:
                print(request.FILES)
                article.pic = article_cd['pic']

            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        # 新增及修改的代码
        categories = category.objects.all()
        context = {
            'article': article,
            'article_post_form': article_post_form,
            'categories': categories,
        }
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)

templates/article/category.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
栏目
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<div class="col-4 m-auto">
<ul class="list-group">
{% for category in categories %}
<li class="list-group-item"><a href="{% url 'article:sort_by_category' category.title %}">{{ category.title }}</a>
{% endfor %}
</ul>
</div>
{% endblock content %}

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="category">栏目</label>
                    <select class="form-control" id="category" name="category">
                        <option value="none">请选择栏目..</option>
                        {% for category in categories %}
                        <option value="{{ category.id }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <div class="form-group col-md-4">
                    <label for="pic">上传图片</label>
                    <input type="file" class="form-control-file" name="pic" id="pic">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <div class="col-9">
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>

            <div>
                <!-- 附加信息 -->
                <span class="badge badge-light text-muted">
                    <i class="fa fa-eye"></i>
                    {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                </span>
                <span class="badge badge-light text-muted">
                    <i class="fa fa-navicon"></i>
                    {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                </span>
                <span class="badge badge-light text-muted">
                    {{ article.updated|date:'Y-m-d' }} 更新
                </span>
                <a href="#" class="badge badge-light text-muted">
                    <i class="fa fa-book"></i>
                    {{article.category}}
                </a>
                <a href="#" class="badge badge-light text-muted" onclick="confirm_delete()">
                    <i class="fa fa-remove "></i>
                    删除文章
                </a>
                <a href="{% url 'article:article_update' article.id %}" class="badge badge-light text-muted">
                    <i class="fa fa-refresh fa-spin"></i>
                    编辑文章
                </a>
            </div>
            <hr>
            <!-- 文章正文 -->
            <div class="col-12">
                <pre style="font-family: inherit; font-size: 1em;">{{ article.body|safe }}</pre>
            </div>
            <hr>
            <!--
            {% if user.is_authenticated %}
            <div>
                <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                我也要发言：
                            </strong>
                        </label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="2"></textarea>
                    </div>
                    提交按钮
                    <button type="submit" class="btn btn-primary ">发送</button>
                </form>
            </div>
            <br>
            {% else %}
            <br>
            <h5 class="row justify-content-center">
                请<a href="{% url 'userprofile:login' %}">登录</a>后回复
            </h5>
            <br>
            {% endif %}



            显示评论
            <h4>共有{{ comments.count }}条评论</h4>
            <div>
                {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> 于
                    <span style="color: green">
                        {{ comment.created|date:"Y-m-d H:i:s" }}
                    </span> 时说：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">{{ comment.body }}</pre>
                {% endfor %}
            </div>-->
        </div>
        <!-- 新增的目录 -->
        <div class="col-3 card d-none d-lg-block mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function (index, layero) {
                // 指定应当前往的 url
                location.href = '{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <!-- 修改，面包屑的href增加search参数
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">
                    最热
                </a>
            </li>
        </ol>
    </nav>-->

    <!-- 新增，搜索栏
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
            </form>
        </div>
    </div>-->

    <!-- 新增，搜索提示语 -->
    {% if search %}
    {% if articles %}
    <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
    <hr>
    {% else %}
    <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
    <hr>
    {% endif %}
    {% endif %}

    <!-- 列表循环 -->
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-12 card mb-2 p-0" style="display: flex">
            <div class="row no-gutters flex-direction: row">
                {% if article.pic %}
                <div class="col-2">
                    <img src="{{ article.pic.url }}" class="card-img">
                </div>
                {% endif %}

                <div class="col">
                    <div class="card-body">
                        <h2>
                            <b>
                                <a href="{% url 'article:article_detail' article.id %}" style="color: black;">
                                    {{ article.title }}
                                </a>
                            </b>
                        </h2>
                        <div>
                            <!-- 附加信息 -->
                            <span class="badge badge-light text-muted">
                                <i class="fa fa-eye"></i>
                                {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                            </span>
                            <span class="badge badge-light text-muted">
                                <i class="fa fa-navicon"></i>
                                {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                            </span>
                            <span class="badge badge-light text-muted">
                                {{ article.updated|date:'Y-m-d' }} 更新
                            </span>
                            {% if article.category %}
                            <a href="{% url 'article:sort_by_category' article.category.title %}"
                                class="badge badge-light text-muted">
                                <i class="fa fa-book"></i>
                                {{article.category}}
                            </a>

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-light">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                    class="btn btn-light">
                    {{ articles.previous_page_number }}
                </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-dark">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                    class="btn btn-light">
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                    class="btn btn-light">
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="category">分类</label>
                    <select class="form-control" id="category" name="category">
                        <option value="none">请选择栏目..</option>
                        {% for category in categories %}
                        <option value="{{ category.id }}" {% if category.id == article.category.id %} selected
                            {% endif %}>
                            {{ category }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body"
                        rows="12">{{ article.body }}</textarea>
                </div>
                <br>
                {% if article.pic %}
                <div class="col-md-4">图片</div>
                <img src="{{ article.pic.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
                {% else %}
                <h5 class="col-md-4">暂无图片</h5>
                {% endif %}
                {% if article.pic %}
                
                    <label for="pic">更改图片</label>
                    <input type="file" class="form-control-file" name="pic" id="pic">
               
                {% else %}
                
                    <label for="pic">上传图片</label>
                    <input type="file" class="form-control-file" name="pic" id="pic">
                
                {% endif %}
                <br>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}